### ISSUE TITLE
V1 Cameras "flashing" image

### ISSUE THREAD

**Issue by MacDaddyFPV** [hd-zero/hdzero-vtx#102]
On the nano/micro v1 there is a constant flashing of the image as if it is trying to change between day and night mode. This is mostly visible when going from sunny to darker areas.

**Comment by T-M-0** [comment]
I can confirm this problem on a nano V1 cam.
It happens when I fly from the sun into the shade on a sunny day.
It starts with FW 06012023 or 22122022

**Comment by mwasserm** [comment]
I also have this issue on a nano v1 camera with original whoop vtx. I noticed the issue after upgrading the vtx and goggle to version 06022023 along with a betaflight flash to 4.4 for the HD OSD. I don't recall the prior vtx firmware version, but it did not exhibit this behavior with the same camera/vtx/goggle combination along with betaflight 4.2. Here is a short video illustrating the issue: https://youtu.be/7xpLYOgoq9g. Several folks have made suggestions to mitigate this flashing, but it really does appear like this is a bug as it occurred only after updating the firmware. Happy to provide more detail or test things out if it would be helpful.

**Comment by ligenxxxx** [comment]
I'm working on it. It takes a little time to debug.

**Comment by ligenxxxx** [comment]
https://github.com/hd-zero/hdzero-vtx/actions/runs/4181809548

**Comment by CyberFpv** [comment]
Got same problem with 3 nano v1 after update to 060123 for my new hdzero goggle.. white balance on or off same things.. flashing

**Comment by ligenxxxx** [comment]
https://github.com/hd-zero/hdzero-vtx/actions/runs/4181959009
Please test the firmware in the link.

**Comment by mwasserm** [comment]
Hi, thank you for such a quick turnaround on this! I only had a few minutes, but I flew before (still had flashes), then flew another battery after updating to this firmware. The flashing appears to be fixed. I'll try and fly again tomorrow to confirm, but so far it looks like it's fixed. I might be mis-remembering, but I still think the nano v1 still looks grainier in the shadows than I remember when I first got it last summer, but it's at least back to the performance immediately before the flashing started.

**Comment by CyberFpv** [comment]
Yayyy.. installed now... and flashing gone.. problem fixed for my first
quad.. leter i test the other 2 cam v1... thank you

Il Sab 18 Feb 2023, 04:39 mwasserm ***@***.***> ha scritto:

**Comment by jsaginario** [comment]
Good for me as well, much improved. Thanks Ligen!

**Comment by csmicfool** [comment]
Confirm this fixed the issue for me too.

Thanks @ligenxxxx !!
