### ISSUE TITLE
VTX off with stick command did not work on on FW 06022023

### ISSUE THREAD

**Issue by T-M-0** [hd-zero/hdzero-vtx#103]
With FW 06022023 I can´t switch the VTX off with stick command.
On FW 06012023 its working.

Tested on Freestyle VTX and Race V2

Smartaudio is not connected.
FC firmware is FETTEC Alpha.
I also tested a few versions. It does not influence the issue.

**Comment by FIynix** [comment]
I can confirm the same problem is still present on firmware V1.1.0.

Using : 
VTX race V2
Camera nano 90
Betaflight 4.2.11 (hobbywing F7)
ELRS 3.1.2

**Comment by ligenxxxx** [comment]
https://github.com/hd-zero/hdzero-vtx/actions/runs/4259879649

**Comment by FIynix** [comment]
We need a way to activate/deactivate 0mw with stick command.
The 0mw stick command was allowing that. 0mw boot option won't work to close the vtx at the end of a race.

**Comment by T-M-0** [comment]
Still not working with the latest firmware.
Tested it also with INAV 6.0.
The VTX does nothing with stickcommand.
Even in the manual it is described that it should work.

**Comment by jissoe** [comment]
I can confirm this is still present on Rev 13042023 with raceV2 vtx. Whoop vtx is working fine.
I noticed the stickcommands are working again when connecting smartaudio.

**Comment by pitts-mo** [comment]
Hello, 
Is this still an issue with VTX firmware Rev_26062023 / 1.3.0  ?

**Comment by T-M-0** [comment]
Yes, its still an issue.
I think that will not be fixed.....

On a whoop board (not the light) it worked with the actual firmware.

Also I talked with the FETTEC programmers, and they say the implemented the MSP protocol like the specs.
MSP V2 actually not implemented.

There must be a little bug on the VTX firmware what causes this issue

**Comment by ligenxxxx** [comment]
@T-M-0 Can this bug still be reproduced?
