### ISSUE TITLE
Feature Request: Spectrum Analyzer / Lost Model Locator

### ISSUE THREAD

**Issue by TwistedFPV** [hd-zero/hdzero-vtx#110]
a menu option for a spectrum analyzer and lost model locator

**Comment by pitts-mo** [comment]
Hello @TwistedFPV , Can you close this issue? 

Neither of these are features can be added on the VTX side. I do see you have already commented on hdzero-goggle issue # 1 for Better spectrum analyzer.  But, maybe you could also add comment to hdzero-goggle issue # 141 for "Quad finder"
Thank you,
-p
