### ISSUE TITLE
ArduPilot - HD Zero - Stick Command Issues (unintended menu opening)

### ISSUE THREAD

**Issue by DroneUnit** [hd-zero/hdzero-vtx#112]
To arm multirotors in ArduPilot (and I believe PX4) you need to hold the left stick (throttle),  right and down for 2+ seconds.  The issue we are having is every time we arm the aircraft this also opens the RunCam camera menu (which is throttle stick right for 3 sec).  Note:  putting "arm" on a dedicated switch is not an option for us. 

How do we prevent this from happening?
a)  Would it be possible to increase the time you need to hold the sticks in side/corner positions for activation of Cam and VTX menus to say 10 seconds (instead of 3s).  It would be great if there was an option to change this time, maybe between 3s or 10s or something like that?
b)  Is there a way to turn off stick commands (we don't have the ability to use Smart Audio).

**Comment by ligenxxxx** [comment]
@DroneUnit 
I have made the conditions for entering the camera menu more stringent. When the left remote sensor moves to the right, the throttle must be in the middle. In fact, the so-called middle range should be quite wide.
Please test following fw.
https://github.com/hd-zero/hdzero-vtx/actions/runs/6258513177
