### ISSUE TITLE
temp_err not reset after entering pit mode

### ISSUE THREAD

**Issue by john-k3nnedy** [hd-zero/hdzero-vtx#119]
I see 

```
temp_err = 1;
```

in a couple of places, for example after entering pit mode, which then applies a `pwr_offset = 10` in `PowerAutoSwitch()`, but don't see `temp_err` revert to 0 anywhere.

This suggests there's always `pwr_offset = 10` applied after having been in pit mode once.

**Comment by ligenxxxx** [comment]
This problem cannot be fixed for now, it is related to the dm6300 chip.

**Comment by john-k3nnedy** [comment]
> This problem cannot be fixed for now, it is related to the dm6300 chip.

Do you have some details on this?

**Comment by ligenxxxx** [comment]
> > This problem cannot be fixed for now, it is related to the dm6300 chip.
> 
> Do you have some details on this?

Unfortunately no.
