### ISSUE TITLE
Firmware V1.3.0 led strip issue

### ISSUE THREAD

**Issue by BadSide84** [hd-zero/hdzero-vtx#147]
With this lastest firmware there is an issue that doesn't permit to change the color via VTX on the led strip on BF v4.4.0, with the vtx firmware v1.2.0 everything works good

CLI COMMAND for the LED

# led
led 0 0,15::CV:13
led 1 1,15::CV:13
led 2 2,15::CV:13
led 3 3,15::CV:13
led 4 4,15::CV:13
led 5 5,15::CV:13
led 6 6,15::CV:13
led 7 7,15::CV:13
led 8 8,15::CV:13
led 9 9,15::CV:13

# color
color 1 240,0,255
color 2 240,0,255
color 3 0,0,255
color 4 0,0,255
color 5 0,0,0
color 7 0,0,0
color 8 0,0,0
color 9 0,0,0
color 10 120,0,255
color 11 330,0,255
color 12 0,0,0
color 13 255,255,255

**Comment by MacDaddyFPV** [comment]
Can confirm, and also a lot of people at our club have the same issue.

**Comment by BadSide84** [comment]
There is the same issue also in firmware v1.5.0 nobody have seen this post i think

**Comment by cruwaller** [comment]
@ligenxxxx this is a BF issue... See  https://github.com/betaflight/betaflight/pull/13096

**Comment by ligenxxxx** [comment]
fixed on BF side.

**Comment by BadSide84** [comment]
> fixed on BF side.

From which release? Because I am running Kaack v4.4.2 and doesn't work

**Comment by ligenxxxx** [comment]
> > fixed on BF side.
> 
> From which release? Because I am running Kaack v4.4.3 and doesn't work

It has not been released by betaflight yet.

**Comment by ligenxxxx** [comment]
set this command line
```
set ledstrip_profile = RACE
set ledstrip_race_color = BLACK
```
With this everything works perfectly
