### ISSUE TITLE
Versioning simplification

### ISSUE THREAD

**Issue by matyas-brenner** [hd-zero/hdzero-vtx#154]
Please consider unifying and simplifying the versioning of VTX firmwares.

Somewhere major.minor.patch is used, somewhere mmddyyy format is used. This date format is IMHO not ideal. If using date format, consider yyyymmdd please. It works much better with sorting (higher the number, newer the firmware).

But most importantly, pick one style of versioning and stick with it everywhere (github, vtx update tool, download page, vtx menus, ...).

The current state of this is so confusing.

I believe that this have a support from community: https://www.facebook.com/groups/hdzero/permalink/679125310782100/

**Comment by ligenxxxx** [comment]
It was achieved.
