### ISSUE TITLE
Lowband on v1.5.0-rc1 

### ISSUE THREAD

**Issue by zandorsp** [hd-zero/hdzero-vtx#169]
To reproduce:
Update a lowband unlocked vtx with v1.5.0-rc1 (tested on Whoop vtx and Race v2).

The lowband channels (L1-L8) doesn't work anymore.

I downgraded to v1.4 and the lowband channels worked again.

I'm using MSP VTX to control the transmission power and channel (Smartaudio not connected on fc)

**Comment by ligenxxxx** [comment]
@zandorsp I use Race v3 VTX and enable msp vtx. After updating to v1.5.0-rc1, lowband is still valid in the VTX menu.
Do you use power on switch or cms(fc) menu?

**Comment by ligenxxxx** [comment]
@zandorsp Please test this fw.
https://github.com/ligenxxxx/hdzero-vtx/actions/runs/6717513533

**Comment by zandorsp** [comment]
> @zandorsp I use Race v3 VTX and enable msp vtx. After updating to v1.5.0-rc1, lowband is still valid in the VTX menu. Do you use power on switch or cms(fc) menu?

To chance channel I used the ExpressLRS VRX menu:
![photo_2023-11-01_14-37-41](https://github.com/hd-zero/hdzero-vtx/assets/53715440/12bc1616-80e8-45e5-bba7-3125749cd5f0)

But I tried on menu too...

**Comment by zandorsp** [comment]
> @zandorsp Please test this fw. https://github.com/ligenxxxx/hdzero-vtx/actions/runs/6717513533

Ok I flashed it and seen all right now.
