### ISSUE TITLE
Use PlatformIO

### ISSUE THREAD

**Issue by brandonrc** [hd-zero/hdzero-vtx#2]
I read that you are looking at replacing Keil IDE with an opensource alternative. 

I believe SDCC is supported with platformIO. 

Also it is easy for new developers to get hacking away and contributing to the project without a huge learning curve from a custom IDE like STM/Microchip/others are known for.

**Comment by saidinesh5** [comment]
I'd say i am 30-35% there, trying to compile this with sdcc(4.2).
I have added a basic Makefile and I am able to compile the sources - I think.
I am currently trying to get the compiled sources to link and create a binary. I haven't done much baremetal programming in C, so I may need to read up on more things to get the linking working, Until then, feel free to review/help me out with the steps.
https://github.com/saidinesh5/hdzero-vtx/tree/sdcc

**Comment by bkleiner** [comment]
i created a basic platfomio project here:
https://github.com/bkleiner/hdzero-vtx/tree/platformio

the pio part it does what it should - however there are still a bunch of issues with using sdcc to compile a flash-able binary

**Comment by SumolX** [comment]
I have a compiling SDCC version of this software and I'm also using cmake.  All that's missing is the conversion from A51 pseudo code to bootloader asm.

https://github.com/SumolX/hdzero-vtx/tree/cmake_support

**Comment by bkleiner** [comment]
retaining compatibility with keil is an interesting angle, however i suspect to take advantage of uVisions debug capabilities they would want to maintain their project files _either way_ so i don't know if cmake actually provides any benefit there.

you might wanna join us on the hdzero discord https://discord.com/invite/kGsnEDMb2V?fbclid=IwAR2eb9m5YUIOLAl5Nq5bY_tuq94awmhvpPFlBz0jKxbktXHVmIOgkSqY-Gw ("open-source" channel)

there are a couple of people there figuring stuff out together.

**Comment by SumolX** [comment]
I use cmake because that is what I'm accustomed too.  I am able to build this source both Linux and macOS.... having windows support would probably be an easy port as well.

**Comment by KarateBrot** [comment]
@SumolX Once building works on Linux you can always use the WSL to also compile on Windows. But having full win support would be the cherry on top.

**Comment by bkleiner** [comment]
PIO comes with seamless cross platform support out of the box ;)

**Comment by SumolX** [comment]
I will have to check it out.  As long as the code compiles and produces a valid binary.... cmake can always be replaced.
