### ISSUE TITLE
Unable to display VTX Power on iNav OSD

### ISSUE THREAD

**Issue by MartinHugh** [hd-zero/hdzero-vtx#203]
Using 
iNav 7.1.1 
vtx firmware 1.6.0
Whoop vtx

The iNav "Video TX Power" OSD element always shows as 0 rather than 1 (25mW) or 2 (200mw)
This works fine in 1.5.0, but not in 1.6.0

I suspect this is to do with the initialisation between the FC and the VTX.

This functionality works OK in the pre 1.6.0 commits, up to and including commit cea7f2c. 
A side effect of the next commit after that (f267b74) was that no iNav OSD was displayed at all
When the OSD was next available (3816938), although the OSD was back, the VTX power now shows zero

That behaviour carried through to the 1.6.0 release.

![image](https://github.com/hd-zero/hdzero-vtx/assets/16915373/81ccb505-d2fd-4750-8206-239e00a17abc)

Changing the video power from iNav has no effect on the displayed value (always 0) with v 1.6.0
Again this works fine on v1.5.0

[1.5.0 test](https://www.mhr.me.uk/vtx-with-1.5.0.mp4)
[1.6.0 test](https://www.mhr.me.uk/vtx-with-1.6.0.mp4)

**Comment by sixtyfive** [comment]
This sounds similar to what I'm experiencing: OSD working fine, but no band, channel or output power shown (the latter being displayed a 0) and no output power change via radio switch possible, either.

**Comment by geoffsim** [comment]
This has been fixed in iNav 8.
