### ISSUE TITLE
Firmware version displayed in VRX does not match files on website

### ISSUE THREAD

**Issue by Yith1** [hd-zero/hdzero-vtx#41]
In the VRX the firmware version number is displayed (XX.YY.ZZ), but only the date is shown in the files on the download page (Rev ddmmyyyy).
This makes it difficult to identify which firmware you have installed as the two things do not correlate in any helpful way.

**Comment by ligenxxxx** [comment]
We can ignore the previous naming rules.

**Comment by ligenxxxx** [comment]
@Yith1 Regarding version numbers, please discuss in #36.
