### ISSUE TITLE
Feature request to update vtx firmware through usb interface

### ISSUE THREAD

**Issue by kakashi2018** [hd-zero/hdzero-vtx#52]
Hi, is it possible to update the vtx modules directly through usb from a computer. With new devices like frsky x20hd which supports hdzero lacks upgrade port for vtx and if the radio is the only thing that one is having like me there is no way to upgdate the firmware on vtx as of now.

**Comment by KarateBrot** [comment]
That's possible via Betaflight's USB passthrough.

But afaik FrSky has to implement it into their flashing app, if they want to support it. Same for HDZero.

**Comment by kakashi2018** [comment]
> That's possible via Betaflight's USB passthrough feature.
> 
> But afaik FrSky has to implement it into their flashing app, if they want to support it. Same for HDZero.

Can you please explain how hdzero vtx firmware update is done via betaflight passthrough or any link related to it?

**Comment by KarateBrot** [comment]
I have no idea. You should ask HDZero about that. They need to make it happen.

**Comment by ligenxxxx** [comment]
https://github.com/bkleiner/hdzero-flasher This might be useful if you have programming background.
Frsky should fix that. All VRXs should have the ability to update the VTX.

**Comment by bkleiner** [comment]
It appears frsky has started shipping usb flashers. Closing.
