### ISSUE TITLE
Betaflight 4.4 HD support

### ISSUE THREAD

**Issue by artusmuc** [hd-zero/hdzero-vtx#69]
HDZero does not support the new OSD configuration in Betaflight 4.4

**Comment by ligenxxxx** [comment]
@artusmuc Please test it.
https://github.com/hd-zero/hdzero-vtx/actions/runs/3779017386

**Comment by lesharodin** [comment]
> @artusmuc Please test it. https://github.com/hd-zero/hdzero-vtx/actions/runs/3779017386
Tested, it works
Before/After pics:
![image](https://user-images.githubusercontent.com/12091173/209571748-01b39969-9119-44cb-a021-d43d88404b60.png)
![image](https://user-images.githubusercontent.com/12091173/209571754-021e65dd-bfe4-4d54-9ad4-25754cc5b57e.png)

**Comment by artusmuc** [comment]
Hello,

Thank you for fast reaction. I can also confirm - it works :)
