### ISSUE TITLE
New "On Time" and "Armed Time" icons appear transposed

### ISSUE THREAD

**Issue by Yith1** [hd-zero/hdzero-vtx#74]
Now I can't be sure, but I assume the timer icon showing a battery would be the "on time" and the one showing a quad would be the "armed time".

However from what I can see the icons are transposed in the VRX4.

Using Race 2 VTX, Runcam Micro V2, HDZero VRX4. All with Rev 22122022 firmware

![image](https://user-images.githubusercontent.com/17471470/209415496-fa40ba86-0d35-41e0-8d55-166e1d4aac33.png)

**Comment by bkleiner** [comment]
Yes, indeed, this was an issue with the original version of this font. find up-to-date versions here https://github.com/hd-zero/hdzero-osd-font-library
