### ISSUE TITLE
Unified vtx firmware file

### ISSUE THREAD

**Issue by oldrootbeer** [hd-zero/hdzero-vtx#79]
If its possible, to make it clean, can we get one unified vtx firmware in future?
Instead of different vtx files, just one to avoid confusion.

**Comment by bkleiner** [comment]
The VTX is pretty resource constrained on the mcu side. Backing everything into a single hex will make that problem worse. 

Imho this problem should be rectified on the tooling side. (Allow loading all hexes to the vrx/goggle, have it detect the vtx type and flash the appropriate firmware)
