### ISSUE TITLE
Compatibility of nano90 with VRX 2sma/4sma

### ISSUE THREAD

**Issue by FIynix** [hd-zero/hdzero-vtx#81]
The VRX 2sma or 4sma actually doesn't work with the nano 90 camera, but works with the event vrx.
Could it be possible to update the vrx 2sma/4sma to make them work with the nano 90 just like the event vrx ?
Many people are keeping their old vrx to use them as event vrx, but this isn't actually possible with the new camera.

**Comment by ligenxxxx** [comment]
Currently these VRXs are available for the nano 90 but converted to a 60Hz display.
