### ISSUE TITLE
Osd freezes then dissappears 

### ISSUE THREAD

**Issue by Muirson** [hd-zero/hdzero-vtx#82]
Fimrware dated "Rev 06012023"
The osd link quality drops to 0 after a few minutes, the osd freezes then drops out.

**Comment by artusmuc** [comment]
I have to say a have a similar experience. In my case i use a Betafpv AIO V2 with 8MB Blackbox and Betaflight 4.4 RC3. If i use 1 kz blackbox its running full after 3 minutes of flight and at this moment OSD disapears.
