### ISSUE TITLE
High contrast video every ~5 power cycles or so on whoop lite vtx.

### ISSUE THREAD

**Issue by Tbell123** [hd-zero/hdzero-vtx#83]
On the whoop lite vtx seeing an extremely high contrast video feed every ~5 power cycles. Its looks like the contrast settings are being messed up, but then power cycling makes it go back to normal. This is using the whoop camera on a 65mm 1s whoop.

![image-6](https://user-images.githubusercontent.com/118670898/211178927-f392cc94-137e-4beb-a327-6bd69fe8bd40.png)
![image-5](https://user-images.githubusercontent.com/118670898/211178930-2a9ae86a-a1b9-4ef2-8e1a-cd55e2d16b19.png)

**Comment by FractalEngineer** [comment]
Contributing a dvr of my similar issue https://youtu.be/TnTCVvRoCfo

**Comment by gizlonk** [comment]
I too am experiencing this same issue. 4-5 packs and the image becomes extremely high contrast. Next cycle and it's OK.

**Comment by iz3man** [comment]
Got that issue too. Was wondering if some settings of the camera were altered. Reconnected the battery and everything was fine again. I was assuming an almost empty battery being the cause. But this doesn't seem to be the case.

**Comment by jgauruder** [comment]
I have the same symptom...indoor 65mm whoop lite vtx build with nano lite cam.  thought maybe I was just powering up while pointing the camera directly at a light in my kitchen or something was causing it randomly to freak out the camera sensor.

**Comment by ligenxxxx** [comment]
DId you try v1.1

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jgauruder** [comment]
@ligenxxxx I will hopefully be able to try that tonight.  Thank you!

**Comment by jgauruder** [comment]
After flashing, I only observed the high contrast once so far.  So not completely eliminated, but so far for me  it seems less frequent than before.  I will see if I can check my DVR to see how many power up/on of vtx was made since update.  I'm guessing maybe 10 total as I tinkered with osd object placement tuning after the firmware update.

**Comment by gizlonk** [comment]
> After flashing, I only observed the high contrast once so far. So not completely eliminated, but so far for me it seems less frequent than before. I will see if I can check my DVR to see how many power up/on of vtx was made since update. I'm guessing maybe 10 total as I tinkered with osd object placement tuning after the firmware update.

This happened to me too. 2nd pack had "drunken camera" and none since then. Worth noting that the camera MAY have been pointed to the light in the room when plugging the battery in.

**Comment by ligenxxxx** [comment]
https://github.com/hd-zero/hdzero-vtx/releases/tag/v1.1.0
