### ISSUE TITLE
Feature request: Irc tramp protocol

### ISSUE THREAD

**Issue by timfredriksson** [hd-zero/hdzero-vtx#85]
It would be wonderful if the vtx could support the irc tramp protocol for us ghost users. It is a feature that is working so awesome in the ghost ecosystem and I miss that I could change channel on the back of the radio a lot.

**Comment by pidschey** [comment]
And one step further a opportunity for ghost rx backpack in the google, that the vtx channel will changed automatically in the google, when changing channel changing by ghost tx

**Comment by ligenxxxx** [comment]
- We are adding the irc tramp protocol.
- Elrs backpack and ghost system do not seem to be universal.So goggle cannot switch channels automatically.

**Comment by ligenxxxx** [comment]
The IRC protocol has been implemented, but it requires VTX hardware support and special ghost fw.
