### ISSUE TITLE
DVR record control by Radio

### ISSUE THREAD

**Issue by artusmuc** [hd-zero/hdzero-vtx#86]
It would be nice if it was possible to start DVR Recording when i flipp a switch on my radio - like it’s with the runcam HD is possible. I can left my fingers at the radio i case i have forgot to start the DVR recording.

**Comment by timfredriksson** [comment]
but isn't that a goggle feature?

**Comment by artusmuc** [comment]
OSD is a google feature. Maybe it will be possible to send a command like this ?

**Comment by rquellet** [comment]
This feature is already implemented as part of Express LRS backpack. Closing this feature request
