### ISSUE TITLE
Bug: Switching Camera Profiles on Micro V2 causes erratic display

### ISSUE THREAD

**Issue by sabshire** [hd-zero/hdzero-vtx#96]
I was playing around, and found that if I switching camera profiles on the Micro V2, and then save&exit, the display goes into an erratic rainbow flashing display that can only be fixed by powering the vtx off and back on.   Running 06012023 firmware.

**Comment by ligenxxxx** [comment]
Please use https://github.com/hd-zero/hdzero-vtx/releases/tag/v1.1.0
