### ISSUE TITLE
VTX/Camera Menu Control/Smart Audio for Wings without Flight Controllers

### ISSUE THREAD

**Issue by CruiseFPV** [hd-zero/hdzero-vtx#99]
Is it possible to access the vtx/camera menu or use smart audio for wings that don't have flight controllers, I was hoping that i could connect SA from my Crossfire Nano to the SA on the HDZero VTX's and access the menu's but i have tried several configurations but unable to have any control

**Comment by ligenxxxx** [comment]
I believe TBS can support it by updating the nano firmware, there is almost nothing I can do.

**Comment by ligenxxxx** [comment]
TBS seems to have fixed this issue, please update your TBS device and confirm.
